### PR TITLE
removed references to hdf5

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
The references to HDF5 are not needed as removing them we still get the same answers. 
Also updated wcoss-phase2 to add a file with full wcoss name (needed for adding capabilities for p3) and fixed warning from ifort.

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Here are the log files for wcoss-phase2 and hera: 
/scratch2/NCEPDEV/climate/Jessica.Meixner/Nov17/s2s-JM-hdf5/log/report-hera.intel-log/rtreport.txt
/marine/noscrub/Jessica.Meixner/ufs-s2s-hdf5-2/log/report-wcoss.phase2-log/rtreport.txt

**Comment by JessicaMeixner-NOAA** [comment]
Solves Issues #2

**Review by jiandewang — COMMENTED** [review]
look good, clean than before

**Review by jiandewang — APPROVED** [review]

**Review by DeniseWorthen — APPROVED** [review]
Looks fine.

**Pull request merged**
